# Generated by Django 3.0.8 on 2020-08-25 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incomeexpenditurestatement',
            name='credit_cards',
        ),
        migrations.RemoveField(
            model_name='incomeexpenditurestatement',
            name='food',
        ),
        migrations.RemoveField(
            model_name='incomeexpenditurestatement',
            name='loans',
        ),
        migrations.RemoveField(
            model_name='incomeexpenditurestatement',
            name='mortgage',
        ),
        migrations.RemoveField(
            model_name='incomeexpenditurestatement',
            name='other',
        ),
        migrations.RemoveField(
            model_name='incomeexpenditurestatement',
            name='rent',
        ),
        migrations.RemoveField(
            model_name='incomeexpenditurestatement',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='incomeexpenditurestatement',
            name='travel',
        ),
        migrations.RemoveField(
            model_name='incomeexpenditurestatement',
            name='utilites',
        ),
    ]
