# Generated by Django 3.0.8 on 2020-08-25 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statement', '0002_auto_20200825_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomeexpenditurestatement',
            name='credit_cards',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='incomeexpenditurestatement',
            name='food',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='incomeexpenditurestatement',
            name='loans',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='incomeexpenditurestatement',
            name='mortgage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='incomeexpenditurestatement',
            name='other',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='incomeexpenditurestatement',
            name='rent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='incomeexpenditurestatement',
            name='salary',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='incomeexpenditurestatement',
            name='travel',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='incomeexpenditurestatement',
            name='utilites',
            field=models.IntegerField(default=0),
        ),
    ]
