# Generated by Django 3.0.8 on 2020-08-25 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statement', '0006_auto_20200825_1722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incomeexpenditurestatement',
            old_name='utilites',
            new_name='utilities',
        ),
    ]
